# This is a reusable workflow to run integration tests.
# This is run for every single map in ci_suite.yml. You might want to edit that instead.
name: Run Integration Tests
on:
  workflow_call:
    inputs:
      major:
        required: false
        type: string
      minor:
        required: false
        type: string
      arg:
        required: false
        default: ALL_TESTS
        type: string

jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3

      - name: Setup BYOND cache
        id: cache-byond
        uses: actions/cache@v3
        with:
          path: ~/BYOND
          key: ${{ runner.os }}-byond-cache-${{ secrets.CACHE_PURGE_KEY }}-${{ hashFiles('dependencies.sh') }}

      - name: Install BYOND
        if: steps.cache-byond.outputs.cache-hit != 'true'
        run: bash tools/ci/install_byond.sh

      - name: Install runtime dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install -o APT::Immediate-Configure=false libssl-dev:i386

      - name: Setup dependencies cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.byond/bin
          key: ${{ runner.os }}-deps-cache-${{ secrets.CACHE_PURGE_KEY }}-${{ hashFiles('dependencies.sh') }}

      - name: Install build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          sudo apt install -o APT::Immediate-Configure=false libgcc-s1:i386 g++-multilib zlib1g-dev:i386
          rustup target add i686-unknown-linux-gnu

      - name: Build auxmos
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bash tools/ci/build_auxmos.sh

      - name: Build rust-g
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: bash tools/ci/build_rust_g.sh

      - name: Setup database
        run: |
          sudo systemctl start mysql
          mysql -u root -proot -e 'CREATE DATABASE tg_ci;'
          mysql -u root -proot tg_ci < SQL/tgstation_schema.sql
          mysql -u root -proot -e 'CREATE DATABASE tg_ci_prefixed;'
          mysql -u root -proot tg_ci_prefixed < SQL/tgstation_schema_prefixed.sql

      - name: Configure version
        if: ${{ inputs.major }}
        run: |
          echo "BYOND_MAJOR=${{ inputs.major }}" >> $GITHUB_ENV
          echo "BYOND_MINOR=${{ inputs.minor }}" >> $GITHUB_ENV

      - name: Compile Tests
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          tools/build/build --ci dm -DCIBUILDING -DANSICOLORS -D${{ inputs.arg }}
      - name: Run Tests
        run: |
          source $HOME/BYOND/byond/bin/byondsetup
          bash tools/ci/run_server.sh
